apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cluster-flux-private-auth
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: *name
  dataFrom:
    - extract:
        key: *name
