---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - pgp:
          # Retired GPG Key
          - 97E082451A4C10B2A9C8681C09DEECDAFFE8153F
          # Yubikey backed GPG Key
          - 07EF252155A078987177E39C11A37ED357D49372
        age:
          - age1ghh53ja2rkyvwc29sxzrz9d9t0f5g0qvkcd9wuem5h2tld5wtyfs8ewz9x
