apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-password-secret
  dataFrom:
    - extract:
        key: grafana-admin-password-secret
