---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: c9s-srlinux-clos
resources:
  - ./namespace.yaml
  - ./topology.yaml
configMapGenerator:
  - name: srlinux-clos-config
    files:
      - n1-cga0-spine.conf=config/n1-cga0-spine.conf
      - n1-cga1-spine.conf=config/n1-cga1-spine.conf
      - n1-a10-leaf-a.conf=config/n1-a10-leaf-a.conf
generatorOptions:
  disableNameSuffixHash: true