---
# yaml-language-server: $schema=https://github.com/srl-labs/clabernetes/blob/v0.3.0/generated/openapi/openapi.json
apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Topology
metadata:
  name: srlinux-clos
  namespace: c9s-srlinux-clos
spec:
  naming: prefixed
  definition:
    containerlab: |-
          name: srlinux-clos
          topology:
            kinds:
              srl:
                image: ghcr.io/nokia/srlinux
              linux:
                image: ghcr.io/hellt/network-multitool
            nodes:
              n1-a10-leaf-a:
                kind: srl
                type: ixrd2
              n1-a10-leaf-b:
                kind: srl
                type: ixrd2
              n1-b10-leaf-a:
                kind: srl
                type: ixrd2
              n1-b10-leaf-b:
                kind: srl
                type: ixrd2
              n1-cga0-spine:
                kind: srl
                type: ixr6
              n1-cga1-spine:
                kind: srl
                type: ixr6
              srv1:
                kind: linux
              srv2:
                kind: linux
            links:
              # inter-switch links
              - endpoints: ["n1-a10-leaf-a:e1-50", "n1-a10-leaf-b:e1-50"]
              - endpoints: ["n1-b10-leaf-a:e1-50", "n1-b10-leaf-b:e1-50"]
              ## cga0 spine
              - endpoints: ["n1-a10-leaf-a:e1-49","n1-cga0-spine:e1-1"]
              - endpoints: ["n1-a10-leaf-b:e1-49","n1-cga0-spine:e1-2"]
              - endpoints: ["n1-b10-leaf-a:e1-49","n1-cga0-spine:e1-3"]
              - endpoints: ["n1-b10-leaf-b:e1-49","n1-cga0-spine:e1-4"]
              ## cga1 spine
              - endpoints: ["n1-a10-leaf-a:e1-48","n1-cga1-spine:e1-1"]
              - endpoints: ["n1-a10-leaf-b:e1-48","n1-cga1-spine:e1-2"]
              - endpoints: ["n1-b10-leaf-a:e1-48","n1-cga1-spine:e1-3"]
              - endpoints: ["n1-b10-leaf-b:e1-48","n1-cga1-spine:e1-4"]
              # server one
              - endpoints: ["srv1:eth1", "n1-a10-leaf-a:e1-1"]
              - endpoints: ["srv1:eth2", "n1-a10-leaf-b:e1-1"]
              # server two
              - endpoints: ["srv2:eth1", "n1-b10-leaf-a:e1-1"]
              - endpoints: ["srv2:eth2", "n1-b10-leaf-b:e1-1"]
  deployment:
    filesFromConfigMap:
      n1-cga0-spine:
        - configMapName: &configMapName srlinux-clos-config
          configMapPath: n1-cga0-spine.conf
          filePath: &filePath /etc/opt/srlinux/config.json
          mode: read