---
# Source: clabernetes/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "clabernetes-service-account"
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-service-account"
    clabernetes/component: service-account
---
# Source: clabernetes/templates/certificate-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-certificate"
    clabernetes/component: certificate
    clabernetes/part-of: manager
  name: "clabernetes-certificate"
  namespace: clab
data: {}
---
# Source: clabernetes/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: clabernetes-config
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-config"
    clabernetes/component: config
data:
  mergeMode: merge
  globalAnnotations: |-
    ---
    {}
  globalLabels: |-
    ---
    {}
  resourcesDefault: |-
    ---
    requests:
      cpu: 200m
      memory: 512Mi
  resourcesByContainerlabKind: |-
    ---
    {}
  nodeSelectorsByImage: |-
    {}
    ---
  privilegedLauncher: "true"
  containerlabDebug: "false"
  inClusterDNSSuffix: svc.cluster.local
  imagePullThroughMode: auto
  launcherImagePullPolicy: IfNotPresent
  launcherLogLevel: info
  naming: prefixed
---
# Source: clabernetes/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-cluster-role"
    clabernetes/component: cluster-role
  name: "clabernetes-cluster-role"
rules:
  - apiGroups:
      - clabernetes.containerlab.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - configmaps
      - services
      - pods
      - persistentvolumeclaims
      - serviceaccounts
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
---
# Source: clabernetes/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-launcher-role"
    clabernetes/component: launcher-role
  name: "clabernetes-launcher-role"
rules:
  - apiGroups:
      - clabernetes.containerlab.dev
    resources:
      - imagerequests
    verbs:
      - get
      - create
  - apiGroups:
      - clabernetes.containerlab.dev
    resources:
      - connectivities
    verbs:
      - get
      - watch
---
# Source: clabernetes/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clabernetes-manager
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-cluster-role-binding"
    clabernetes/component: cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: "clabernetes-service-account"
    namespace: clab
roleRef:
  kind: ClusterRole
  name: "clabernetes-cluster-role"
  apiGroup: rbac.authorization.k8s.io
---
# Source: clabernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clabernetes-http
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-manager"
    clabernetes/component: manager-http
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10443
  selector:
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-manager"
    clabernetes/component: manager
---
# Source: clabernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clabernetes-ui
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    app.kubernetes.io/name: "clabernetes-ui"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-ui"
    clabernetes/component: ui
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3000
  selector:
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-ui"
    clabernetes/component: ui
---
# Source: clabernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clabernetes-manager
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    app.kubernetes.io/name: "clabernetes-manager"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-manager"
    clabernetes/component: manager
spec:
  selector:
    matchLabels:
      clabernetes/app: clabernetes
      release: clabernetes
      clabernetes/component: manager
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        chart: "clabernetes-0.3.1"
        release: clabernetes
        heritage: Helm
        revision: "1"
        app.kubernetes.io/name: "clabernetes-manager"
        clabernetes/app: clabernetes
        clabernetes/name: "clabernetes-manager"
        clabernetes/component: manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    clabernetes/app: clabernetes
                    clabernetes/name: "clabernetes-manager"
                    clabernetes/component: manager
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    clabernetes/app: clabernetes
                    clabernetes/name: "clabernetes-manager"
                    clabernetes/component: manager
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 10
      serviceAccountName: "clabernetes-service-account"
      initContainers:
        - name: init
          image: "ghcr.io/srl-labs/clabernetes/clabernetes-manager:0.5.0"
          imagePullPolicy: IfNotPresent
          command: ["/clabernetes/manager", "run", "--initializer"]
          env:
            - name: APP_NAME
              value: clabernetes
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLIENT_OPERATION_TIMEOUT_MULTIPLIER
              value: "1"
            - name: MANAGER_LOGGER_LEVEL
              value: info
            - name: CONTROLLER_LOGGER_LEVEL
              value: info
            - name: LAUNCHER_IMAGE
              value: "ghcr.io/srl-labs/clabernetes/clabernetes-launcher:0.3.1"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
      containers:
        - name: manager
          image: "ghcr.io/srl-labs/clabernetes/clabernetes-manager:0.5.0"
          imagePullPolicy: IfNotPresent
          command: ["/clabernetes/manager", "run"]
          env:
            - name: APP_NAME
              value: clabernetes
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLIENT_OPERATION_TIMEOUT_MULTIPLIER
              value: "1"
            - name: MANAGER_LOGGER_LEVEL
              value: info
            - name: CONTROLLER_LOGGER_LEVEL
              value: info
            - name: LAUNCHER_IMAGE
              value: "ghcr.io/srl-labs/clabernetes/clabernetes-launcher:0.3.1"
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
          ports:
          - name: http
            containerPort: 10443
          livenessProbe:
            httpGet:
              path: /alive
              port: 10443
              scheme: HTTPS
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
---
# Source: clabernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clabernetes-ui
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    app.kubernetes.io/name: "clabernetes-ui"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-ui"
    clabernetes/component: ui
spec:
  selector:
    matchLabels:
      clabernetes/app: clabernetes
      release: clabernetes
      clabernetes/component: ui
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        chart: "clabernetes-0.3.1"
        release: clabernetes
        heritage: Helm
        revision: "1"
        app.kubernetes.io/name: "clabernetes-ui"
        clabernetes/app: clabernetes
        clabernetes/name: "clabernetes-ui"
        clabernetes/component: ui
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    clabernetes/app: clabernetes
                    clabernetes/name: "clabernetes-ui"
                    clabernetes/component: ui
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    clabernetes/app: clabernetes
                    clabernetes/name: "clabernetes-ui"
                    clabernetes/component: ui
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 10
      serviceAccountName: "clabernetes-service-account"
      containers:
        - name: ui
          image: "ghcr.io/srl-labs/clabernetes/clabernetes-ui:0.3.1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
---
# Source: clabernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clabernetes-ui
  namespace: clab
  labels:
    chart: "clabernetes-0.3.1"
    release: clabernetes
    heritage: Helm
    revision: "1"
    app.kubernetes.io/name: "clabernetes-ui"
    clabernetes/app: clabernetes
    clabernetes/name: "clabernetes-ui"
    clabernetes/component: ui
spec:
  ingressClassName: nginx
  rules:
    - host: ui.clabernetes.containerlab.dev
      http:
        paths:
          - backend:
              service:
                name: clabernetes-ui
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
