interface ethernet-1/1 {
    vlan-tagging true
    subinterface 1000 {
        type bridged
        admin-state enable
        vlan {
            encap {
                untagged {
                }
            }
        }
    }
}
interface ethernet-1/49 {
    admin-state enable
    subinterface 0 {
        admin-state enable
        ipv4 {
            address 192.168.0.1/31 {
            }
        }
    }
}
interface system0 {
    admin-state enable
    subinterface 0 {
        admin-state enable
        ipv4 {
            address 172.20.3.1/32 {
            }
        }
    }
}
tunnel-interface vxlan1 {
    vxlan-interface 1000 {
        type bridged
        ingress {
            vni 1000
        }
    }
}
network-instance mvrf-elliana {
    type mac-vrf
    admin-state enable
    interface ethernet-1/1.1000 {
    }
    vxlan-interface vxlan1.1000 {
    }
    protocols {
        bgp-evpn {
            bgp-instance 1 {
                admin-state enable
                vxlan-interface vxlan1.1000
                evi 1000
            }
        }
        bgp-vpn {
            bgp-instance 1 {
                route-target {
                    export-rt target:2031:2032
                    import-rt target:2031:2032
                }
            }
        }
    }
}
network-instance default {
    interface ethernet-1/49.0 {
    }
    interface system0.0 {
    }
    protocols {
        isis {
            instance ISISUnderlay {
                admin-state enable
                level-capability L2
                net [ 49.0001.0000.0001.0001.00 ]
                ipv4-unicast {
                    admin-state enable
                }
                interface system0.0 {
                    admin-state enable
                    passive true
                    ipv4-unicast {
                        admin-state enable
                    }
                    level 2 {
                    }
                }
                interface ethernet-1/49.0 {
                    circuit-type point-to-point
                    ipv4-unicast {
                        admin-state enable
                    }
                    level 2 {
                    }
                }
            }
        }
        bgp {
            autonomous-system 64525
            router-id 172.20.3.1
            group iBGPEVPNOverlay {
                export-policy all
                import-policy all
                peer-as 64525
                ipv4-unicast {
                    admin-state disable
                }
                evpn {
                    admin-state enable
                }
                local-as 64525 {
                }
                timers {
                    minimum-advertisement-interval 1
                }
            }
            neighbor 172.20.3.2 {
                peer-group iBGPEVPNOverlay
                transport {
                    local-address 172.20.3.1
                }
            }
        }
    }
}
routing-policy {
    policy all {
        default-action {
            accept {
            }
        }
    }
}
